const rockBands = [
    'Queen',
    'Metallica',
    'ACDC',
    'Nirvana',
    'Guns n Roses',
    'Black Sabbath',
    'Green Day',
    'Iron Maiden',
    'Linkin Park',
    'Aerosmith',
    'Red Hot Chili Peppers',
    'Foo Fighters',
    'Avenged Sevenfold',
    'System of a Down',
    'Three Days Grace',
    'Deep Purple',
    'Muse',
    'Skillet',
    'Alice in Chains',
    'Король и Шут',
    'Noize MC',
    'Ария',
    'Judas Priest',
    'Kiss',
    'Coldplay',
    'Disturbed',
    'Megadeth',
    'Arctic Monkeys',
    'Bullet for My Valentine',
    'The Offspring',
    'Marilyn Manson',
    'Korn',
    'Papa Roach',
    'Imagine Dragons',
    'Alter Bridge',
    'Shinedown',
    'Rage Against the Machine',
    'Slipknot',
    '311',
    'Кино',
    'The Killers',
    'Anthrax',
    'Twenty One Pilots',
    'Scorpions',
    'Slayer',
    'A Day to Remember',
    'The Rasmus',
    'Sabaton',
    'Limp Bizkit',
    'Rammstein',
    'Pantera',
    'Nightwish',
    'Seether',
    'Keane',
    'Bad Omens',
    'Motley Crue'
];